;(c)AlexCorp. 1994
; The offsets of BIOS variables (from segment 0)

   BIOS_mode           EQU  0449h
   BIOS_width          EQU  044Ah
   BIOS_bytesPerPage   EQU  044Ch
   BIOS_regSAR         EQU  044Eh
   BIOS_curs           EQU  0450h
   BIOS_cursUp         EQU  0460h
   BIOS_cursDown       EQU  0461h
   BIOS_actPage        EQU  0462h
   BIOS__3x4           EQU  0463h
   BIOS_regMCR         EQU  0465h
   BIOS_regCSR         EQU  0466h
   BIOS_length         EQU  0484h
   BIOS_highChar       EQU  0485h
   BIOS_EGAinf         EQU  0487h








